language: cpp
sudo: true
solution: burst-miner.sln
dist: trusty
compiler: gcc
env: CXX=g++-5 CXXFLAGS="-std=c++14"
os: linux
group: stable
cache:
  directories:
  - $HOME/poco
before_install:
- ./install-poco.sh
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
script:
- make
- cp poco-1.7.6-all ~/poco
