language: cpp
sudo: true
solution: burst-miner.sln
dist: trusty
compiler: gcc
env: CXX=g++-5 CXXFLAGS="-std=c++14"
os: linux
group: stable
cache:
  directories:
  - $TRAVIS_BUILD_DIR/poco-1.7.6-all
before_install:
- if [ ! -d "poco-1.7.6-all" ]; then ./install-poco.sh; fi
- if [ -d "poco-1.7.6-all" ]; then cd poco-1.7.6-all && sudo ldconfig && sudo make install; fi
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
script: make
